config/routes.rb
Rails.application.routes.draw do
  resources :prompts
  resources :journal_entries
  resources :categories
  resources :users

  get "/login", to: "users#login", as: "login"
  post "/handle_login", to: 'users#handle_login'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
 

app/models/category.rb
class Category < ApplicationRecord
    has_many :journal_entries
    has_many :users, through: :journal_entries
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user
  belongs_to :category
  # belongs_to :prompt
end

app/models/prompt.rb
class Prompt < ApplicationRecord
    # has_many :journal_entries
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :journal_entries
    has_many :categories, through: :journal_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories =  Category.all 
    end

    def show
        @category = Category.find(params[:id]) 
        @journal_entries = @category.journal_entries
    end

    # def update
    #     @category = Category.find(params[:id])
    #     @category = Category.update(category_params)
    # end

    # def delete
    #     @category = Category.find(params[:id])
    #     @category.destroy
    #     redirect_to categories_path
    # end

    private

    def category_params
        params.require(:category).permit(:name)
    end

end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
    def index
        @journal_entries = JournalEntry.all
        @categories = Category.all
    end

    def show
        @journal_entry = JournalEntry.find(params[:id])
       
    end
    
    def new 
        # @prompts = Prompt.all
        @user = User.last
        @current_user = session[:user_id]
        @categories = Category.all
        @journal_entry = JournalEntry.new
    end
    
    def create
        @journal_entry = JournalEntry.create(journal_entry_params)
        redirect_to journal_entries_path
    end

    def edit
        @journal_entry = JournalEntry.find(params[:id])
    end

    def update
        @journal_entry = JournalEntry.find(params[:id])
        @journal_entry = JournalEntry.update(journal_entry_params)
        redirect_to journal_entry_path
    end

    def destroy
        @journal_entry = JournalEntry.find(params[:id])
        @journal_entry.destroy
        redirect_to journal_entries_path
    end

    private

    def journal_entry_params 
        params.require(:journal_entry).permit(:prompt_id, :user_id, :category_id, :content)
       end
    



end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
    def index 
        @prompts = Prompt.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # def new 
    #     @user = User.new
    # end

    def create 
        @user = User.create(user_params)
        redirect_to categories_path(@user)
    end

    def login
    end

    def handle_login
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to new_journal_entry_path
        else
            redirect_to login_path
        end
        end

    private 

   def user_params 
    params.require(:user).permit(:username, :password)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.erb
<h1>Journal Page</h1>

<% @categories.each do |category| %>
    <p> <%= link_to category.name,new_journal_entry_path(category) %> </p>
    <p hidden>  </p>
    <%end%>

app/views/journal_entries/edit.erb
<h2> Edit Journal <h2>

<%=form_for @journal_entry do |f| %>
     <p><%=f.label :content %></p>
     <p><%=f.text_field :content %></p>


    
   
    <%= f.submit "Finish"%>
    
    <%end%>

app/views/journal_entries/index.erb
<h1> Heres all your past Journals </h1>

<% @journal_entries.each do |journal_entry| %>
<p> <%= link_to journal_entry.category.name, journal_entry%> </p>


<%end%>

<div class="animated bounce"><%= button_to "Write Another", new_journal_entry_path(@journal_entry), :method => :get %></div>

app/views/journal_entries/new.erb
<h2> New Journal <h2>



<%=form_for @journal_entry do |f| %>
    <%=f.label :category %>
    <%=f.collection_select :category_id, @categories, :id, :name%><br>
  <%=f.hidden_field :user_id, value: @current_user %><br>
    <div class="animated bounce"><%=f.label :content %></div>
    <p><%=f.text_area :content, :cols => "100", :rows => "25" %></p>
    
    
   
    <%= f.submit "Finish"%>
    
    <%end%>

    

app/views/journal_entries/show.erb
<h3> Content Page </h3>

<%= @journal_entry.content %>

<p><%= button_to "edit", edit_journal_entry_path(@journal_entry), :method => :get %></p>
<p><%= button_to "delete", journal_entry_path(@journal_entry), :method => :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journalapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login.erb
<div class="animated heartBeat"><h1> Journal App </h1></div>

<%= form_tag "/handle_login" do %>
    <%= label_tag :username %> 
	<%= text_field_tag :username %>
	<%= label_tag :password %>
	<%= password_field_tag :password %>
    <%= submit_tag "Login" %>
<% end %>